### ISSUE TITLE
MAC版酸酸乳有计划吗？

### ISSUE THREAD

**Issue by josangmi** [ihciah/rabbit-tcp#1]
问一下，你的服务端和酸酸乳是分别两个不同的docker吗？ 如果服务器端已经安装好酸酸乳的话怎么处理。 还有mac的酸酸乳能用吗？

**Comment by ihciah** [comment]
这个加速并不区分被加速的流量，只要是 TCP 就行。
所以是可以的。

关于部署的说明文档里有写。
