### ISSUE TITLE
rabbit-tcp服务端的连接目标是由rabbit-tcp客户端指定的？

### ISSUE THREAD

**Issue by Tom-Plants** [ihciah/rabbit-tcp#18]
很奇怪，配置服务端的时候看不到 _目标服务器 ip_ 与 _端口_ 。

但是能在配置客户端的时候看见**DEST=YOUR-SS-ADDR**，很奇怪，为什么要这么设计？

**Comment by f4nff** [comment]
有啥可疑问的，作者这样设计，更灵活，
服务端只是服务端，
就像一个socks5代理服务端一样，
连接的目的性是客户端指定的。
