### ISSUE TITLE
加速多个端口配置文件怎么写？

### ISSUE THREAD

**Issue by LGTMXD** [ihciah/rabbit-tcp#2]
比如80和443都加速，谢谢🤔

**Comment by ihciah** [comment]
服务端不指定待加速服务，目标地址是客户端传过去的。
所以部署上可以这样（RC指RabbitTCP Client，RS指RabbitTCP Server，C、S指目标服务的客户端与服务端）：
C1--RC1--RS--S1
C2--RC2--RS--S2
即RC数目=C数目，RS可以共用。

如果你想要的是加速某ShadowSocks，推荐的做法是在同一台机器上部署RS，同一个服务器的不同端口可以共用一个RS。
