### ISSUE TITLE
使用了一段时间以后 日志 提示 通道破损。

### ISSUE THREAD

**Issue by online2311** [ihciah/rabbit-tcp#4]
配置文件：
rabbit-client-8636:
  image: ihciah/rabbit
  ports:
    - "8636:8636/tcp"
  environment:
    - MODE=c
    - PASSWORD=Nodecloud
    - RABBITADDR=47.x.x.x:443
    - LISTEN=:8636
    - DEST=52.x.x.x.x:8636
    - TUNNELN=6
    - VERBOSE=2
  restart: always

日志内容 ：[Client]2019/10/25 03:11:17 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49301: write tcp 172.17.0.2:8636->58.59.4.253:49301: write: broken pipe.
[Client]2019/10/25 03:11:17 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49300: write tcp 172.17.0.2:8636->58.59.4.253:49300: write: broken pipe.
[Client]2019/10/25 03:11:42 [Error] Error when relay client: read tcp 172.17.0.2:8636->58.59.4.253:49357: read: connection reset by peer.
[Client]2019/10/25 03:11:42 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49358: write tcp 172.17.0.2:8636->58.59.4.253:49358: write: broken pipe.
[Client]2019/10/25 03:11:42 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49360: write tcp 172.17.0.2:8636->58.59.4.253:49360: write: broken pipe.
[Client]2019/10/25 03:11:42 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49359: write tcp 172.17.0.2:8636->58.59.4.253:49359: write: broken pipe.
[Client]2019/10/25 03:12:07 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49230: write tcp 172.17.0.2:8636->58.59.4.253:49230: write: broken pipe.
[Client]2019/10/25 03:12:42 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49436: write tcp 172.17.0.2:8636->58.59.4.253:49436: write: broken pipe.
[Client]2019/10/25 03:12:42 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49433: write tcp 172.17.0.2:8636->58.59.4.253:49433: write: broken pipe.
[Client]2019/10/25 03:13:07 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49381: write tcp 172.17.0.2:8636->58.59.4.253:49381: write: broken pipe.
[Client]2019/10/25 03:13:07 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49380: write tcp 172.17.0.2:8636->58.59.4.253:49380: write: broken pipe.
[Client]2019/10/25 03:13:07 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49383: write tcp 172.17.0.2:8636->58.59.4.253:49383: write: broken pipe.
[Client]2019/10/25 03:13:07 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49382: write tcp 172.17.0.2:8636->58.59.4.253:49382: write: broken pipe.
[Client]2019/10/25 03:13:08 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49391: write tcp 172.17.0.2:8636->58.59.4.253:49391: write: broken pipe.
[Client]2019/10/25 03:13:08 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49390: write tcp 172.17.0.2:8636->58.59.4.253:49390: write: broken pipe.
[Client]2019/10/25 03:13:11 [Error] Error when relay client: read tcp 172.17.0.2:8636->58.59.4.253:49561: read: connection reset by peer.
[Client]2019/10/25 03:13:12 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49525: write tcp 172.17.0.2:8636->58.59.4.253:49525: write: broken pipe.
[Client]2019/10/25 03:13:13 [Error] Error when relay client: readfrom tcp 172.17.0.2:8636->58.59.4.253:49549: write tcp 172.17.0.2:8636->58.59.4.253:49549: write: broken pipe.

**Comment by online2311** [comment]
ip 58.59.4.253 是终端用户 使用IP地址

**Comment by ihciah** [comment]
这个错误是说rabbit client写数据到ss client出现问题。
这种情况是有可能出现的，比如客户端发出请求后远程会回传数据，在数据接收完毕之前两个client之间的连接中断。
如果这种情况不影响使用那么可以忽略。如果导致了使用问题请回复一下，我后续查一下代码。

**Comment by online2311** [comment]
就是因为TCP连接被中断，客户端就会卡死。引起无法通信，无法运维代理基于通信。

**Comment by online2311** [comment]
就是因为TCP连接被中断，客户端就会卡死。无法继续通信，引起业务中断。我的理解是 C与S 是多连接，为什么C到终端也是多连接？

**Comment by ihciah** [comment]
这个问题可以提供稳定复现的输入吗？我这边log里也会有但是并不影响使用。
C到终端是单个连接。
可以尝试改大ss客户端超时时间。

**Comment by online2311** [comment]
已经把相关信息发送到您邮箱请查阅，如果需要其他信息我来提供。

**Comment by online2311** [comment]
over
